sonar.organization=zoumana001
sonar.projectKey=zoumana001_microservices-demo
sonar.projectName=Zoum-Boutique-Frontend
sonar.sources=src/frontend
sonar.exclusions=**/vendor/**,**/*_test.go,**/node_modules/**
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8