apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: zoum-elasticsearch
  namespace: logging
spec:
  version: 8.14.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.roles: ["master", "data", "ingest"]
        xpack.security.enabled: true
        xpack.security.http.ssl.enabled: false
        xpack.security.transport.ssl.enabled: true
      podTemplate:
        metadata:
          labels:
            app: elasticsearch
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 1Gi
                  cpu: 500m
                limits:
                  memory: 2Gi
                  cpu: "1"
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms512m -Xmx512m"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
            storageClassName: gp2
