apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: zoum-kibana
  namespace: logging
spec:
  version: 8.14.0
  count: 1
  elasticsearchRef:
    name: zoum-elasticsearch
  config:
    telemetry.enabled: false
    logging.root.level: warn
  podTemplate:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=350"